In [1]:
import pandas as pd
import numpy as np

In [2]:
data_path="../data/"
outputs_path="../outputs/"
test_set=pd.read_csv(outputs_path+"general/test_set_final.csv")
train_set=pd.read_csv(outputs_path+"general/train_set_final.csv")
dev_set=pd.read_csv(outputs_path+"general/dev_set_final.csv")
test_set=test_set.iloc[:2000]
low_ocurrence=pd.read_csv(data_path+"test_data/low_occurrence_annotated.csv")

In [3]:
low_ocurrence=low_ocurrence.rename(columns={'Most Related SG goal':'goal1_raw',
       '(if exists) 2nd Related SG Goal':'goal2_raw', '(if exists) 3rd Related SG Goal':'goal3_raw'})
low_ocurrence=low_ocurrence.rename(columns={"SG_or_not":"label"})
low_ocurrence["label"]=low_ocurrence["label"].fillna(0)
low_ocurrence.abstract_clean=low_ocurrence.abstract_clean.fillna('')
low_ocurrence=low_ocurrence.assign(text=low_ocurrence.title_clean+". "+low_ocurrence.abstract_clean)

df_all_goals=pd.concat([dev_set,train_set,test_set])

In [4]:
mapping_sdg={'sdg1': 'No Poverty',
 'sdg2': 'Zero Hunger',
 'sdg3': 'Good Health and Well-Being',
 'sdg4': 'Quality Education',
 'sdg5': 'Gender Equality',
 'sdg6': 'Clean Water and Sanitation',
 'sdg7': 'Affordable and Clean Energy',
 'sdg8': 'Decent Work and Economic Growth',
 'sdg9': 'Industry, Innovation and Infrastructure',
 'sdg10': 'Reduced Inequalities',
 'sdg11': 'Sustainable Cities and Communities',
 'sdg12': 'Responsible Consumption and Production',
 'sdg13': 'Climate Action',
 'sdg14': 'Life Below Water',
 'sdg15': 'Life on Land',
 'sdg16': 'Peace, Justice and Strong Institutions',
 'sdg17': 'Partnership for the Goals'
}

In [5]:
df_all_goals.goal1_raw=df_all_goals.goal1_raw.fillna('')
df_all_goals.goal2_raw=df_all_goals.goal2_raw.fillna('')
df_all_goals.goal3_raw=df_all_goals.goal3_raw.fillna('')
df_all_goals=df_all_goals.assign(goal1=np.where(df_all_goals['goal1_raw'].str.lower().str.contains("education"),'Quality Education',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("poverty"),'No Poverty',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("hunger"),'Zero Hunger',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("clean_water"),'Clean Water and Sanitation',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("clean_energy"),'Affordable and Clean Energy',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("life_land"),'Life on Land',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("marine_life"),'Life Below Water',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("health"),'Good Health and Well-Being',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("climate"),'Climate Action',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("peace|privacy|disinformation_and_fake_news|deception|hate"),'Peace, Justice and Strong Institutions',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("social biases|race & identity"),'Reduced Inequalities',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("industry|innovation|research"),'Industry, Innovation and Infrastructure',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("sustainable cities|sustainable_cities"),'Sustainable Cities and Communities',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("gender"),'Gender Equality',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("decent work|decent_work_and_economy"),'Decent Work and Economic Growth',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("partnership"),'Partnership for the Goals',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("responsible_consumption_and_production"),'Responsible Consumption and Production',
                    np.where(df_all_goals['goal1_raw'].str.lower().str.contains("reduced|social_equality"),'Reduced Inequalities',''
                          )))))))))))))))))))

df_all_goals=df_all_goals.assign(goal2=np.where(df_all_goals['goal2_raw'].str.lower().str.contains("education"),'Quality Education',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("poverty"),'No Poverty',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("hunger"),'Zero Hunger',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("clean_water"),'Clean Water and Sanitation',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("clean_energy"),'Affordable and Clean Energy',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("life_land"),'Life on Land',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("marine_life"),'Life Below Water',         
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("health"),'Good Health and Well-Being',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("climate"),'Climate Action',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("peace|privacy|disinformation_and_fake_news|deception|hate"),'Peace, Justice and Strong Institutions',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("social biases|race & identity"),'Reduced Inequalities',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("industry|innovation|research"),'Industry, Innovation and Infrastructure',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("sustainable cities|sustainable_cities"),'Sustainable Cities and Communities',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("gender"),'Gender Equality',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("decent work|decent_work_and_economy"),'Decent Work and Economic Growth',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("partnership"),'Partnership for the Goals',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("responsible_consumption_and_production"),'Responsible Consumption and Production',
                    np.where(df_all_goals['goal2_raw'].str.lower().str.contains("reduced|social_equality"),'Reduced Inequalities',''
                          )))))))))))))))))))

df_all_goals=df_all_goals.assign(goal3=np.where(df_all_goals['goal3_raw'].str.lower().str.contains("education"),'Quality Education',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("poverty"),'No Poverty',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("hunger"),'Zero Hunger',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("clean_water"),'Clean Water and Sanitation',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("clean_energy"),'Affordable and Clean Energy',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("life_land"),'Life on Land',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("marine_life"),'Life Below Water',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("health"),'Good Health and Well-Being',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("climate"),'Climate Action',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("peace|privacy|disinformation_and_fake_news|deception|hate"),'Peace, Justice and Strong Institutions',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("social biases|race & identity"),'Reduced Inequalities',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("industry|innovation|research"),'Industry, Innovation and Infrastructure',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("sustainable cities|sustainable_cities"),'Sustainable Cities and Communities',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("gender"),'Gender Equality',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("decent work|decent_work_and_economy"),'Decent Work and Economic Growth',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("partnership"),'Partnership for the Goals',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("responsible_consumption_and_production"),'Responsible Consumption and Production',
                    np.where(df_all_goals['goal3_raw'].str.lower().str.contains("reduced|social_equality"),'Reduced Inequalities',''
                          )))))))))))))))))))

In [6]:
df_all_goals=df_all_goals.loc[df_all_goals.label==1]

In [7]:
df_group=pd.concat([df_all_goals.loc[:,['ID','goal1','year']],df_all_goals.loc[:,['ID','goal2','year']].rename(columns={'goal2':'goal1'}),df_all_goals.loc[:,['ID','goal3','year']].rename(columns={'goal3':'goal1'})])

In [8]:
df_group=df_group.loc[df_group.goal1!='']

In [9]:
df_group=df_group.rename(columns={'goal1':'Goal'})

In [10]:
df_papers=pd.concat([df_group]).reset_index(drop=True)

In [11]:
df_papers=df_papers.loc[~df_papers.year.isna()]

In [12]:
df_papers.year=df_papers.year.apply(int)

In [13]:
df_agg=df_papers.groupby(['Goal','year']).ID.count().reset_index()


df_agg=df_agg.assign(total=df_agg.groupby(['year']).ID.transform(lambda x:x.sum()))

df_agg=df_agg.assign(total_max=df_agg.groupby(['year']).ID.transform(lambda x:x.max()))

df_agg=df_agg.assign(proportion=df_agg.ID/df_agg.total)
df_agg=df_agg.assign(proportion_max=df_agg.ID/df_agg.total_max)

df_agg=df_agg.rename(columns={'ID':'papers'})

In [14]:
df_agg

,Goal,year,papers,total,total_max,proportion,proportion_max
0,Climate Action,2020,1,109,38,0.009174,0.026316
1,Decent Work and Economic Growth,1997,1,2,1,0.500000,1.000000
2,Decent Work and Economic Growth,2000,1,5,1,0.200000,1.000000
3,Decent Work and Economic Growth,2004,1,12,4,0.083333,0.250000
4,Decent Work and Economic Growth,2005,1,5,2,0.200000,0.500000
...,...,...,...,...,...,...,...
140,Responsible Consumption and Production,2021,1,113,50,0.008850,0.020000
141,Sustainable Cities and Communities,2011,1,14,6,0.071429,0.166667
142,Sustainable Cities and Communities,2014,1,34,13,0.029412,0.076923
143,Sustainable Cities and Communities,2015,1,18,7,0.055556,0.142857
144,Sustainable Cities and Communities,2020,2,109,38,0.018349,0.052632

## all years

In [15]:
df_agg_total=df_papers.groupby(['Goal']).ID.count().reset_index()
df_agg_total=df_agg_total.assign(total=df_agg_total.ID.sum())
df_agg_total=df_agg_total.assign(proportion=df_agg_total.ID/df_agg_total.total)
df_agg_total=df_agg_total.assign(total_max=df_agg_total.ID.max())
df_agg_total=df_agg_total.assign(proportion_max=df_agg_total.ID/df_agg_total.total_max)
df_agg_total=df_agg_total.rename(columns={'ID':'papers'})

df_agg_total=df_agg_total.assign(year="All years")

In [16]:
df_agg_final=pd.concat([df_agg,df_agg_total])

In [17]:
df_agg.loc[df_agg.year==2010]

,Goal,year,papers,total,total_max,proportion,proportion_max
31,Good Health and Well-Being,2010,5,14,5,0.357143,1.0
60,"Industry, Innovation and Infrastructure",2010,2,14,5,0.142857,0.4
92,"Peace, Justice and Strong Institutions",2010,3,14,5,0.214286,0.6
114,Quality Education,2010,4,14,5,0.285714,0.8

In [18]:
df_agg_final.loc[df_agg_final.year=="All years"]

,Goal,year,papers,total,total_max,proportion,proportion_max
0,Climate Action,All years,1,655,202,0.001527,0.004950
1,Decent Work and Economic Growth,All years,14,655,202,0.021374,0.069307
2,Gender Equality,All years,18,655,202,0.027481,0.089109
3,Good Health and Well-Being,All years,202,655,202,0.308397,1.000000
4,"Industry, Innovation and Infrastructure",All years,82,655,202,0.125191,0.405941
5,Partnership for the Goals,All years,16,655,202,0.024427,0.079208
6,"Peace, Justice and Strong Institutions",All years,189,655,202,0.288550,0.935644
7,Quality Education,All years,96,655,202,0.146565,0.475248
8,Reduced Inequalities,All years,31,655,202,0.047328,0.153465
9,Responsible Consumption and Production,All years,1,655,202,0.001527,0.004950
10,Sustainable Cities and Communities,All years,5,655,202,0.007634,0.024752

In [19]:
df_agg_final.Goal.value_counts()

Industry, Innovation and Infrastructure    30
Good Health and Well-Being                 29
Quality Education                          24
Peace, Justice and Strong Institutions     20
Reduced Inequalities                       14
Partnership for the Goals                  13
Decent Work and Economic Growth            11
Gender Equality                             6
Sustainable Cities and Communities          5
Climate Action                              2
Responsible Consumption and Production      2
Name: Goal, dtype: int64

In [20]:
mapping_all={
'No Poverty':'G1. No Poverty',
'Zero Hunger':'G2. No Hunger',
'Good Health and Well-Being':'G3. Good Health and Well-Being',
'Quality Education':'G4. Quality Education',
'Gender Equality':'G5. Gender Equality',
'Clean Water and Sanitation':'G6. Clean Water and Sanitation',
'Affordable and Clean Energy':'G7. Affordable and Clean Energy',
'Decent Work and Economic Growth':'G8. Decent Work and Economic Growth',
'Industry, Innovation and Infrastructure':'G9. Industry, Innovation and Infrastructure',
'Industry, Innovation and Infrastrucure':'G9. Industry, Innovation and Infrastructure',
'Reduced Inequalities':'G10. Reduced Inequalities',
'Sustainable Cities and Communities':'G11. Sustainable Cities and Communities',
'Responsible Consumption and Production':'G12. Responsible Consumption and Production',
'Climate Action':'G13. Climate Action',
'Life Below Water':'G14. Life Below Water',
'Life on Land':'G15. Life on Land',
'Peace, Justice and Strong Institutions':'G16. Peace, Justice and Strong Institutions',
'Partnership for the Goals':'G17. Partnership for the Goals'
}

In [21]:
df_agg_final['goal_long']=df_agg_final.Goal.replace(mapping_all)

In [22]:
from itertools import product

In [23]:
df_dict=pd.DataFrame(list(product(list(df_agg_final.year.unique()), list(df_agg_final.Goal.unique()))), columns=['year', 'Goal'])

In [24]:
df_dict['goal_long']=df_dict.Goal.replace(mapping_all)

In [25]:
df_dict=df_dict.merge(df_agg_final,on=['year','Goal','goal_long'],how='left')

In [26]:
df_dict.papers=df_dict.papers.fillna(0)

In [27]:
mapping_all_n={
'No Poverty':'01',
'Zero Hunger':'02',
'Good Health and Well-Being':'03',
'Quality Education':'04',
'Gender Equality':'05',
'Clean Water and Sanitation':'06',
'Affordable and Clean Energy':'07',
'Decent Work and Economic Growth':'08',
'Industry, Innovation and Infrastructure':'09',
'Industry, Innovation and Infrastrucure':'09',
'Reduced Inequalities':'10',
'Sustainable Cities and Communities':'11',
'Responsible Consumption and Production':'12',
'Climate Action':'13',
'Life Below Water':'14',
'Life on Land':'15',
'Peace, Justice and Strong Institutions':'16',
'Partnership for the Goals':'17'
}

In [28]:
df_dict['goal_number']=df_dict.Goal.replace(mapping_all_n)

In [29]:
df_dict

,year,Goal,goal_long,papers,total,total_max,proportion,proportion_max,goal_number
0,2020,Climate Action,G13. Climate Action,1.0,109.0,38.0,0.009174,0.026316,13
1,2020,Decent Work and Economic Growth,G8. Decent Work and Economic Growth,2.0,109.0,38.0,0.018349,0.052632,08
2,2020,Gender Equality,G5. Gender Equality,6.0,109.0,38.0,0.055046,0.157895,05
3,2020,Good Health and Well-Being,G3. Good Health and Well-Being,33.0,109.0,38.0,0.302752,0.868421,03
4,2020,"Industry, Innovation and Infrastructure","G9. Industry, Innovation and Infrastructure",12.0,109.0,38.0,0.110092,0.315789,09
...,...,...,...,...,...,...,...,...,...
424,All years,"Peace, Justice and Strong Institutions","G16. Peace, Justice and Strong Institutions",189.0,655.0,202.0,0.288550,0.935644,16
425,All years,Quality Education,G4. Quality Education,96.0,655.0,202.0,0.146565,0.475248,04
426,All years,Reduced Inequalities,G10. Reduced Inequalities,31.0,655.0,202.0,0.047328,0.153465,10
427,All years,Responsible Consumption and Production,G12. Responsible Consumption and Production,1.0,655.0,202.0,0.001527,0.004950,12
428,All years,Sustainable Cities and Communities,G11. Sustainable Cities and Communities,5.0,655.0,202.0,0.007634,0.024752,11

df_agg_final.Goal=df_agg_final.Goal.replace({'Zero Hunger':'No Hunger'})

In [30]:
df_dict=df_dict.sort_values(['goal_number'])

In [31]:
df_dict

,year,Goal,goal_long,papers,total,total_max,proportion,proportion_max,goal_number
256,2010,Good Health and Well-Being,G3. Good Health and Well-Being,5.0,14.0,5.0,0.357143,1.000000,03
223,2003,Good Health and Well-Being,G3. Good Health and Well-Being,1.0,5.0,3.0,0.200000,0.333333,03
179,1996,Good Health and Well-Being,G3. Good Health and Well-Being,1.0,3.0,1.0,0.333333,1.000000,03
366,1993,Good Health and Well-Being,G3. Good Health and Well-Being,0.0,NaN,NaN,NaN,NaN,03
25,2000,Good Health and Well-Being,G3. Good Health and Well-Being,1.0,5.0,1.0,0.200000,1.000000,03
...,...,...,...,...,...,...,...,...,...
82,2014,Partnership for the Goals,G17. Partnership for the Goals,0.0,NaN,NaN,NaN,NaN,17
170,1985,Partnership for the Goals,G17. Partnership for the Goals,0.0,NaN,NaN,NaN,NaN,17
401,1991,Partnership for the Goals,G17. Partnership for the Goals,1.0,1.0,1.0,1.000000,1.000000,17
115,2017,Partnership for the Goals,G17. Partnership for the Goals,0.0,NaN,NaN,NaN,NaN,17
214,2002,Partnership for the Goals,G17. Partnership for the Goals,0.0,NaN,NaN,NaN,NaN,17

In [32]:
df_dict.to_json(outputs_path+"/sg_visualization/proportions_years_gold.json",orient="records")